Release/0.1.0
cmpsc-481-s22-m1/GatorConfig pull request #22
Opened 2022-01-26 22:19 UTC by ColemanKobe

# GatorGradle Configuration in Assignments

## Description

This release is meant to enable GatorGradle in certain assignments by creating a GitHub Actions configuration file and a GatorGradle configuration file through two means: a GUI and a CLI.

### Type of Change

- [x] Feature
- [] Bug fix
- [ ] Documentation

## Contributors

- @ullrichd21 
- @WesleyL30 
- @favourojo 
- @PaigeCD 
- @ColemanKobe 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

2022-01-26 22:22 UTC, favourojo submitted a review, later dismissed
Everything looks good!

2022-01-27 02:41 UTC, Michionlion requested changes
Great work for a first MVP! There are a few global issues along with the specific feedback I've given above.

First, your main package should use a descriptive name -- if you use `src`, then once you release this tool anyone who wanted to include your module as a library (even if that isn't the only intended use case) would need to do `import src`. That isn't very user-friendly! In addition, it isn't conventional. Instead, you should use a name like `gatorconfig`.

Second, I could find no documentation on how to run or use your tool or GUI. There should be some kind of `README.md` at least.

Thirdly, your Typer CLI object should be registered as a script in `pyproject.toml` -- see the Poetry [documentation](https://python-poetry.org/docs/pyproject/#scripts) as well as the relevant [tutorial](https://typer.tiangolo.com/tutorial/package/) in the Typer documentation. This will make using your CLI as a user very easy!

Lastly, I would suggest thinking about ways you can make this code platform-agnostic. Right now it will always depend on PyQt, which to my understanding is only available on Linux. This would restrict users to only those using Linux for their assignment development. Separating out platform-specific dependencies or somehow encapsulating the core functionality in a separate package would be ideal.

Overall, this is an excellent MVP! I look forward to seeing your fixes and final release candidate, and your future work next sprint.

2022-01-27 02:41 UTC, Michionlion commented on src/gator_config.py
> +            check = input(f"Enter a check for {item} (type \"stop\" to move on): ")
Instead of using `stop` to move on, as a customer it would be nice if I could just enter an "empty" check (just hitting enter without typing anything) to move on.

2022-01-27 02:41 UTC, Michionlion commented on src/gator_config.py
> +    actions_configuration.create_configuration_file('../.github/workflows/grade.yml')
Your CLI should be the single, sole "main function" -- this entrypoint should **just** call `cli()`. In `cli_input()`, you should call everything that needs to execute, including this `create_configuration_file` function.

2022-01-27 02:41 UTC, Michionlion commented on src/gator_yaml.py
> +class GatorYaml:
You should consider writing this library as a static set of functions, instead of capturing state with a class object. That would enable both 1) isolated testing, and 2) encapsulated functionality. Using keyword arguments for things like `spaces` or `indent` would also be similar to what other I/O libraries do. However, implementing this may be a significant refactoring process, so it's not essential.

2022-01-27 02:41 UTC, Michionlion commented on src/gator_yaml.py
> +        """Output key and value if a keyword"""
I am dubious about the value of handling keywords like this. I think a simpler and more efficient method would be to simply take a string (presumably obtained from the user) to directly add to `self.output` as a "check line", with the indentation to use obtained from context. This would maintain backward-compatibility for any format changes, as well as be even more flexible.

2022-01-27 02:41 UTC, Michionlion commented on src/gui/form.py
> +                     "idcommand": "echo $TRAVIS_REPO_SLUG",
`idcommand`, `executables`, and `reflection` should be left blank (i.e. unspecified) if they are not configured, as they can both be confusing to the user, and cause errors (especially in the case of `idcommand`) if specified incorrectly for the user's context.

2022-01-27 02:41 UTC, Michionlion commented on tests/test_actions_configuration.py
> +    src.actions_configuration.create_configuration_file('config.yml')
There are no assertions in this test; additionally, it pollutes the main repository with a `config.yml` file when tests are run. This test should be refactored to either use a `tmpdir` to write the workflow to, or to mock `open`.

2022-01-27 02:41 UTC, Michionlion commented on tests/test_gator_config.py
> +    output = pathlib.Path.cwd().joinpath("gatorgrader.yml")
This test, if run, would pollute the main repository with a `gatorgrader.yml` file. Instead, either use a `tmpdir` fixture to create temporary files for testing, or mock `open`.

2022-01-27 02:41 UTC, Michionlion commented on tests/test_gator_config.py
> +    output = pathlib.Path.cwd().joinpath("gatorgrader.yml")
Ditto on above feedback.

2022-01-27 02:41 UTC, Michionlion commented on pyproject.toml
You should add a name, authors, description, and other metadata for your project. Eventually you will need to publish this project on PyPI, and this metadata will be useful!

2022-01-27 05:38 UTC, mariakimheinert requested changes
Great work on this release, everyone! Please let me know if you have any questions about this feedback.

2022-01-27 05:38 UTC, mariakimheinert commented on src/gator_yaml.py
> +class GatorYaml:
Consider doing some of this refactoring during the next sprint, if time allows.

2022-01-27 05:38 UTC, mariakimheinert commented on .gitignore
> +*.yml
All YAML files should not be ignored; if there are specific YAML files you do not want to end up in the repository, just make sure not to `git add` them.

2022-01-27 15:07 UTC, ullrichd21 commented on src/gui/form.py
> +                     "idcommand": "echo $TRAVIS_REPO_SLUG",
Left over from testing. Removed.

2022-01-28 01:50 UTC, mariakimheinert requested changes
There are a few changes that should be made before this release is merged. Please see my feedback below and let me know if you have any questions.

2022-01-28 01:50 UTC, mariakimheinert commented on config.yml
> +name: Grade
This generated output should not be stored in this repository.

2022-01-28 01:50 UTC, mariakimheinert commented on pyproject.toml
> +requests-mock = "^1.9.3"
This should be in dev dependencies.

2022-01-28 01:50 UTC, mariakimheinert commented on requirements.txt
> +pytest~=6.2.5
This shouldn't be needed.

2022-01-28 01:50 UTC, mariakimheinert commented on tests/test_gator_config.py
> +@pytest.fixture()
Any specific reason why this is marked as a fixture? If not, this should be removed.

2022-01-28 01:50 UTC, mariakimheinert commented on tests/test_gator_config.py
> +@pytest.fixture()
Remove this?

2022-01-28 01:50 UTC, mariakimheinert commented on tests/test_gator_config.py
> +@pytest.fixture()
Remove this also.

2022-01-28 01:57 UTC, ColemanKobe commented on tests/test_gator_config.py
> +@pytest.fixture()
The three test cases are marked as a fixture because errors will pop up like the following: `TypeError: 'str' object is not callable` and `AttributeError: 'LocalPath' object has no attribute 'joinpath'`

2022-01-28 01:57 UTC, ColemanKobe commented on tests/test_gator_config.py
> +@pytest.fixture()
Otherwise, they pass

2022-01-28 02:03 UTC, Michionlion requested changes
Overall I think this looks good, but there are a few key issues that need to be resolved: see my feedback below.

2022-01-28 02:03 UTC, Michionlion commented on requirements.txt
> +pytest~=6.2.5
Poetry should replace any need for a `requirements.txt`.

2022-01-28 02:03 UTC, Michionlion commented on tests/test_gator_config.py
> +@pytest.fixture()
This is a significant problem with your test suite: by marking these functions as 'fixtures' they are no longer tests, but fixture factory functions, which is definitely not what you intended. These lines should be removed.

2022-01-28 02:04 UTC, Michionlion commented on pyproject.toml
> +requests = "^2.27.1"
@ColemanKobe `requests` probably should be in your regular dependencies -- it's used in your tool's implementation for scraping releases. It's just `requests-mock` that is a test dependency.

2022-01-28 02:06 UTC, Michionlion commented on gatorconfig/gator_config.py
> +    actions_configuration.create_configuration_file('../.github/workflows/grade.yml')
Otherwise, the script set up in `pyproject.toml` will not run the actions creation function.

2022-01-28 02:19 UTC, PaigeCD commented on README.md
> +`Wrote file to: C:\Users\<YOUR PATH>\GatorConfig\gatorgrader.yml`
Yes, at the moment this is the expected output. If it is alright for the sake of this release, we will make this adjustment during the upcoming sprint.

2022-01-28 02:29 UTC, Michionlion commented on README.md
> +`Wrote file to: C:\Users\<YOUR PATH>\GatorConfig\gatorgrader.yml`
Sounds good!

2022-01-28 02:49 UTC, PaigeCD commented on gatorconfig/scrape_releases.py
> +import requests
I have added a link to this comment in issue #11 so that this can be consider in the upcoming sprint.

2022-01-28 03:48 UTC, mariakimheinert requested changes
Just a couple of minor fixes and you'll be good to go.

2022-01-28 03:48 UTC, mariakimheinert commented on gatorgrader.yml
> +name: Project
This generated file should be removed. (In the future, avoid running `git add .` or `git add -A` and, instead, stage files directly).

2022-01-28 03:48 UTC, mariakimheinert commented on tests/test_gator_config.py
> +def test_cli_no_input(mocker: MockerFixture, tmpdir: MockerFixture):
`tmpdir` is not of type `MockerFixture`, so it shouldn't be type-hinted as such.

2022-01-28 03:51 UTC, mariakimheinert approved these changes
Good to go! Great work, y'all.

2022-01-28 03:52 UTC, WesleyL30 commented on gatorgrader.yml
> +name: Project
That's interesting, the .gitignore should have `*.yml`

2022-01-28 03:54 UTC, ColemanKobe commented on gatorgrader.yml
> +name: Project
We had to remove it

2022-01-28 03:56 UTC, Michionlion approved these changes
Excellent work, everyone!

2022-01-28 03:57 UTC, merged