Release/v1.0.0
cmpsc-481-s22-m1/GatorConfig pull request #63
Opened 2022-02-03 14:44 UTC by ullrichd21

# Release v1.0.0

## Description

#### New Features:

- GatorYAML removed locally, replaced by GatorYAML dependency
- Added default assignment name functionality
- Added more detailed help text
- Added a dropdown for GatorGrader and GatorGradle in the GUI
- Changed format for default checks
- Updated from PyQt5 -> PyQt6
- GUI now available as an **optional** install!

#### Bug Fixes / Minor Changes:
- Various extraneous files removed
- Fixed destructive file creation
- Fixed errors in help text
- Fixed styling issues
- Fixed PyQt6 test failures
- Fixed various issues in test cases

### Type of Change

- [x] Feature
- [x] Bug fix
- [ ] Documentation

## Contributors

- @ullrichd21 
- @WesleyL30 
- @ColemanKobe 
- @PaigeCD 
- @favourojo 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

2022-02-04 01:16 UTC, mariakimheinert requested changes
Excellent work on this final release! I have one small requested fix.

2022-02-04 01:16 UTC, mariakimheinert commented on tests/test_gator_config.py
> +    test_file = test_dir / "config" / "gatorgrader.yml"
If testing the overwriting function, a file at this path should be created before running the program.

2022-02-04 01:25 UTC, mariakimheinert requested changes
One more requested change--please update your `README.md` so that it contains all required parts of project documentation: https://mariakimheinert.com/software-innovation-2/assessment-strategy/final-release/#project-documentation

2022-02-04 01:35 UTC, Michionlion requested changes
Great work on these improvements! There are a few bugs I've found, along with some code improvements; I've listed the feedback that isn't line-specific here, and you can read the rest of the feedback below.

1) Your README.md will become the displayed front page of your tool on PyPI, so it should be user-facing and include details on how to install the tool with `pip` or `pipx`.

2) Creating a GitHub Action will fail with an error if `.github/workflows` does not exist. You should automatically create that directory, if it doesn't exist.

3) Your implementation currently writes `commits: <value>` to the header of `gatorgrader.yml`, but that is invalid configuration -- there is no `commits` parameter for GatorGradle. I mentioned this below as well, but you should think about removing this option all-together.

4) In the GUI, you cannot select a file (only folders) in Reflection's **Open** button-triggered file chooser.

5) When using the GUI, any checks added end up using the full absolute path to the file in `gatorgrader.yml`, instead of a path relative to the root of the assignment.

6) When a file is in the root directory of the assignment as passed as an argument to `--file`, an empty `:` is added in the `gatorgrader.yml` output, like:

```
README.md:
    :
        --description "Confirm the file exists" ConfirmFileExists
```

Overall, this tool looks extremely useful and full-featured, and although there are a few bugs that are affect the user experience pretty heavily, they should be relatively straightforward to fix. I'm looking forward to reviewing your final release!

2022-02-04 01:35 UTC, Michionlion commented on gatorconfig/gator_config.py
> +        print(f"'gatorgrader.yml' already exists within {config_dir}")
This entire block is duplicated below (starting on line 58), so your main generation runs twice. In fact, when running your tool this can be seen in the fact that it will *always* complain about `gatorgrader.yml` already existing (because it was created in this first run, and so the second finds that it already exists).

2022-02-04 01:35 UTC, Michionlion commented on gatorconfig/gator_config.py
> +    brk: bool = typer.Option(True, "--break", help="Enables break"),
Instead of making this option enable break, it should be called `--no-break` and set the `break` value in the configuration to `false` if it is specified (i.e. if it is true); as it is now, there is no way for a user to create a configuration file with `break: false` in it. This is pretty important to the functionality of your program, so let me know if I can clarify this.

2022-02-04 01:35 UTC, Michionlion commented on gatorconfig/gator_config.py
> +            check = input(f"Enter a check for {item} (Press 'Enter' to move on): ")
This should probably say "to move to the next file", as "move on" is ambiguous.

2022-02-04 01:41 UTC, Michionlion commented on gatorconfig/gui/form.py
> +                            "executables": "",
This results in `idcommand:` in the header of `gatorgrader.yml`, which is invalid configuration.

2022-02-04 02:29 UTC, Michionlion reviewed
I missed this before, but the GUI is asking for a GatorGradle version, however your tool does not output a `build.gradle` file (which is what would contain that version); if you've completed everything else, that may be a feature that could be added.

2022-02-04 21:56 UTC, PaigeCD commented on pyproject.toml
> +repository = "https://github.com/cmpsc-481-s22-m1/GatorConfig"
Are there any classifiers in particular that you would recommend for this tool?

2022-02-04 23:13 UTC, ColemanKobe commented on pyproject.toml
> +repository = "https://github.com/cmpsc-481-s22-m1/GatorConfig"
Hopefully, this link can provide some ideas: https://pypi.org/classifiers/

2022-02-05 00:29 UTC, Michionlion requested changes
Great work everyone! Just a few small, quick changes. Additionally, although it doesn't affect your build in any way, it would be nice to update the version in `pyproject.toml` to be current.

2022-02-05 00:29 UTC, Michionlion commented on gatorconfig/gator_config.py
> +                "readme": gen_readme,
This ends up generating `readme: False/True` in `gatorgrader.yml`, which is not valid configuration.

2022-02-05 00:29 UTC, Michionlion commented on gatorconfig/gui/form.py
>                              "startup": self.startup_script_text.text(),
`startup` should be handled like `idcommand` and the others, since there is no default value.
Additionally, it would be nice if `break` defaulted to checked.

2022-02-05 00:29 UTC, Michionlion commented on gatorconfig/gui/form.py
> +
```suggestion
full_data = self.insert_reflection(full_data)
```

2022-02-05 00:29 UTC, Michionlion commented on gatorconfig/gui/form.py
> +
Seems like you forgot to call this function.

2022-02-05 01:05 UTC, ColemanKobe commented on gatorconfig/gator_config.py
> +                "readme": gen_readme,
For me, it doesn't do that, at least with this PR I just merged

2022-02-05 03:34 UTC, Michionlion requested changes
Looks good -- minor GUI issue though! After that's fixed you should be good to go.

2022-02-05 03:34 UTC, Michionlion commented on gatorconfig/gui/form.py
> +    def insert_checked_commands(self, data):
This new method (which is a better way to do this than what you had before) is not called.

2022-02-05 03:34 UTC, Michionlion commented on gatorconfig/gui/form.py
> +    def insert_checked_commands(self, data):
Although definitely not something you should fix in this release, it would be nice to have some kind of way to test these things in (at least) an integration test for the GUI.

2022-02-05 03:58 UTC, Michionlion approved these changes, later dismissed
Looks good!

2022-02-05 04:23 UTC, mariakimheinert requested changes

2022-02-05 04:23 UTC, mariakimheinert commented on gatorconfig/gui/cwidgets.py
> +        return self.line.text()
Currently, running the GUI produces this error:

```
ykim@aldenv8362 GatorConfig % poetry run gatorconfig --overwrite --gui
Traceback (most recent call last):
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/homepage.py", line 31, in <lambda>
    submit_button = QPushButton("Submit", clicked=lambda: self.submit_form(form))
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/homepage.py", line 48, in submit_form
    data = form.submit_form()
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/form.py", line 178, in submit_form
    full_data = self.insert_checked_commands(full_data)
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/form.py", line 199, in insert_checked_commands
    if self.reflection.text() != "":
AttributeError: 'CFilePicker' object has no attribute 'text'
zsh: abort      poetry run gatorconfig --overwrite --gui
ykim@aldenv8362 GatorConfig % poetry run gatorconfig --overwrite --gui
Traceback (most recent call last):
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/homepage.py", line 31, in <lambda>
    submit_button = QPushButton("Submit", clicked=lambda: self.submit_form(form))
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/homepage.py", line 48, in submit_form
    data = form.submit_form()
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/form.py", line 178, in submit_form
    full_data = self.insert_checked_commands(full_data)
  File "/Users/ykim/CoursePrep/s22m1/481/project-testing/GatorConfig/gatorconfig/gui/form.py", line 200, in insert_checked_commands
    data["header"]["reflection"] = self.reflection.text()
AttributeError: 'CFilePicker' object has no attribute 'text'
zsh: abort      poetry run gatorconfig --overwrite --gui
```

To resolve it, you can just change the name of this function. Additionally, the path should be relative, so `os.path.relpath` should be used.
```suggestion
    def text(self):
        """Return the file path from the text box"""
        if self.line.text() == "":
            return ""
        return os.path.relpath(self.line.text())
```
(The check for an empty string is because `relpath` will not accept empty strings.)

2022-02-05 04:32 UTC, mariakimheinert approved these changes
Awesome work, y'all. Thanks for all your hard work!

2022-02-05 04:33 UTC, Michionlion approved these changes
I think there might be a few other edge cases in the GUI (it can be a bit complicated to test!), but this should be good to go, and extremely useful for professors! Thank you for all your hard work, everyone!

2022-02-05 04:35 UTC, merged